// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChittyChatServiceClient is the client API for ChittyChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChittyChatServiceClient interface {
	PublishMessage(ctx context.Context, in *PostMessage, opts ...grpc.CallOption) (*PostResponse, error)
	BroadcastAllMessages(ctx context.Context, in *BroadcastAllRequest, opts ...grpc.CallOption) (*BroadcastAllResponse, error)
	NewClientJoined(ctx context.Context, in *NewClientJoinedRequest, opts ...grpc.CallOption) (*NewClientJoinedResponse, error)
	ClientLeave(ctx context.Context, in *ClientLeaveRequest, opts ...grpc.CallOption) (*ClientLeaveResponse, error)
	//Not thought out yet(WIP)
	BroadcastJoin(ctx context.Context, in *Empty, opts ...grpc.CallOption) (ChittyChatService_BroadcastJoinClient, error)
	BroadcastLeave(ctx context.Context, in *Empty, opts ...grpc.CallOption) (ChittyChatService_BroadcastLeaveClient, error)
}

type chittyChatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChittyChatServiceClient(cc grpc.ClientConnInterface) ChittyChatServiceClient {
	return &chittyChatServiceClient{cc}
}

func (c *chittyChatServiceClient) PublishMessage(ctx context.Context, in *PostMessage, opts ...grpc.CallOption) (*PostResponse, error) {
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, "/ChittyChatService/PublishMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chittyChatServiceClient) BroadcastAllMessages(ctx context.Context, in *BroadcastAllRequest, opts ...grpc.CallOption) (*BroadcastAllResponse, error) {
	out := new(BroadcastAllResponse)
	err := c.cc.Invoke(ctx, "/ChittyChatService/BroadcastAllMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chittyChatServiceClient) NewClientJoined(ctx context.Context, in *NewClientJoinedRequest, opts ...grpc.CallOption) (*NewClientJoinedResponse, error) {
	out := new(NewClientJoinedResponse)
	err := c.cc.Invoke(ctx, "/ChittyChatService/NewClientJoined", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chittyChatServiceClient) ClientLeave(ctx context.Context, in *ClientLeaveRequest, opts ...grpc.CallOption) (*ClientLeaveResponse, error) {
	out := new(ClientLeaveResponse)
	err := c.cc.Invoke(ctx, "/ChittyChatService/ClientLeave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chittyChatServiceClient) BroadcastJoin(ctx context.Context, in *Empty, opts ...grpc.CallOption) (ChittyChatService_BroadcastJoinClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChittyChatService_ServiceDesc.Streams[0], "/ChittyChatService/BroadcastJoin", opts...)
	if err != nil {
		return nil, err
	}
	x := &chittyChatServiceBroadcastJoinClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChittyChatService_BroadcastJoinClient interface {
	Recv() (*NewClientJoinedResponse, error)
	grpc.ClientStream
}

type chittyChatServiceBroadcastJoinClient struct {
	grpc.ClientStream
}

func (x *chittyChatServiceBroadcastJoinClient) Recv() (*NewClientJoinedResponse, error) {
	m := new(NewClientJoinedResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chittyChatServiceClient) BroadcastLeave(ctx context.Context, in *Empty, opts ...grpc.CallOption) (ChittyChatService_BroadcastLeaveClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChittyChatService_ServiceDesc.Streams[1], "/ChittyChatService/BroadcastLeave", opts...)
	if err != nil {
		return nil, err
	}
	x := &chittyChatServiceBroadcastLeaveClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChittyChatService_BroadcastLeaveClient interface {
	Recv() (*ClientLeaveResponse, error)
	grpc.ClientStream
}

type chittyChatServiceBroadcastLeaveClient struct {
	grpc.ClientStream
}

func (x *chittyChatServiceBroadcastLeaveClient) Recv() (*ClientLeaveResponse, error) {
	m := new(ClientLeaveResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChittyChatServiceServer is the server API for ChittyChatService service.
// All implementations must embed UnimplementedChittyChatServiceServer
// for forward compatibility
type ChittyChatServiceServer interface {
	PublishMessage(context.Context, *PostMessage) (*PostResponse, error)
	BroadcastAllMessages(context.Context, *BroadcastAllRequest) (*BroadcastAllResponse, error)
	NewClientJoined(context.Context, *NewClientJoinedRequest) (*NewClientJoinedResponse, error)
	ClientLeave(context.Context, *ClientLeaveRequest) (*ClientLeaveResponse, error)
	//Not thought out yet(WIP)
	BroadcastJoin(*Empty, ChittyChatService_BroadcastJoinServer) error
	BroadcastLeave(*Empty, ChittyChatService_BroadcastLeaveServer) error
	mustEmbedUnimplementedChittyChatServiceServer()
}

// UnimplementedChittyChatServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChittyChatServiceServer struct {
}

func (UnimplementedChittyChatServiceServer) PublishMessage(context.Context, *PostMessage) (*PostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishMessage not implemented")
}
func (UnimplementedChittyChatServiceServer) BroadcastAllMessages(context.Context, *BroadcastAllRequest) (*BroadcastAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastAllMessages not implemented")
}
func (UnimplementedChittyChatServiceServer) NewClientJoined(context.Context, *NewClientJoinedRequest) (*NewClientJoinedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewClientJoined not implemented")
}
func (UnimplementedChittyChatServiceServer) ClientLeave(context.Context, *ClientLeaveRequest) (*ClientLeaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientLeave not implemented")
}
func (UnimplementedChittyChatServiceServer) BroadcastJoin(*Empty, ChittyChatService_BroadcastJoinServer) error {
	return status.Errorf(codes.Unimplemented, "method BroadcastJoin not implemented")
}
func (UnimplementedChittyChatServiceServer) BroadcastLeave(*Empty, ChittyChatService_BroadcastLeaveServer) error {
	return status.Errorf(codes.Unimplemented, "method BroadcastLeave not implemented")
}
func (UnimplementedChittyChatServiceServer) mustEmbedUnimplementedChittyChatServiceServer() {}

// UnsafeChittyChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChittyChatServiceServer will
// result in compilation errors.
type UnsafeChittyChatServiceServer interface {
	mustEmbedUnimplementedChittyChatServiceServer()
}

func RegisterChittyChatServiceServer(s grpc.ServiceRegistrar, srv ChittyChatServiceServer) {
	s.RegisterService(&ChittyChatService_ServiceDesc, srv)
}

func _ChittyChatService_PublishMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChittyChatServiceServer).PublishMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ChittyChatService/PublishMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChittyChatServiceServer).PublishMessage(ctx, req.(*PostMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChittyChatService_BroadcastAllMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChittyChatServiceServer).BroadcastAllMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ChittyChatService/BroadcastAllMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChittyChatServiceServer).BroadcastAllMessages(ctx, req.(*BroadcastAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChittyChatService_NewClientJoined_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewClientJoinedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChittyChatServiceServer).NewClientJoined(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ChittyChatService/NewClientJoined",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChittyChatServiceServer).NewClientJoined(ctx, req.(*NewClientJoinedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChittyChatService_ClientLeave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientLeaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChittyChatServiceServer).ClientLeave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ChittyChatService/ClientLeave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChittyChatServiceServer).ClientLeave(ctx, req.(*ClientLeaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChittyChatService_BroadcastJoin_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChittyChatServiceServer).BroadcastJoin(m, &chittyChatServiceBroadcastJoinServer{stream})
}

type ChittyChatService_BroadcastJoinServer interface {
	Send(*NewClientJoinedResponse) error
	grpc.ServerStream
}

type chittyChatServiceBroadcastJoinServer struct {
	grpc.ServerStream
}

func (x *chittyChatServiceBroadcastJoinServer) Send(m *NewClientJoinedResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ChittyChatService_BroadcastLeave_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChittyChatServiceServer).BroadcastLeave(m, &chittyChatServiceBroadcastLeaveServer{stream})
}

type ChittyChatService_BroadcastLeaveServer interface {
	Send(*ClientLeaveResponse) error
	grpc.ServerStream
}

type chittyChatServiceBroadcastLeaveServer struct {
	grpc.ServerStream
}

func (x *chittyChatServiceBroadcastLeaveServer) Send(m *ClientLeaveResponse) error {
	return x.ServerStream.SendMsg(m)
}

// ChittyChatService_ServiceDesc is the grpc.ServiceDesc for ChittyChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChittyChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ChittyChatService",
	HandlerType: (*ChittyChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishMessage",
			Handler:    _ChittyChatService_PublishMessage_Handler,
		},
		{
			MethodName: "BroadcastAllMessages",
			Handler:    _ChittyChatService_BroadcastAllMessages_Handler,
		},
		{
			MethodName: "NewClientJoined",
			Handler:    _ChittyChatService_NewClientJoined_Handler,
		},
		{
			MethodName: "ClientLeave",
			Handler:    _ChittyChatService_ClientLeave_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BroadcastJoin",
			Handler:       _ChittyChatService_BroadcastJoin_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BroadcastLeave",
			Handler:       _ChittyChatService_BroadcastLeave_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpc/proto.proto",
}
